version: "3"

services:
  client:
    build: ./client
    image: jezdufourq/assignment1_client:latest
    ports:
      - 8080:8080
    volumes:
      - ./client:/data

  server:
    build: ./server
    image: jezdufourq/assignment1_server:latest
    ports:
    - 3000:3000
    volumes:
    - ./server:/data
    depends_on:
    - client